# -*- coding: utf-8 -*-
"""YOLO_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yhylu1HqZcC82_BqaTYS-x2c_dIUNWK2
"""

import os
import numpy as np
import tensorflow as tf
from google.colab import drive
import pathlib

device_name = tf.test.gpu_device_name()

if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')

print('Found GPU at: {}'.format(device_name))

drive.mount('/content/drive')

!pip install ultralytics

import ultralytics
ultralytics.checks()

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Car_dataset/Cars Detection/
!ls

from ultralytics import YOLO
model = YOLO('yolov8m.pt')
model.info()

!yolo task=detect mode=train model=yolov8m.pt data=data.yaml epochs=100 imgsz=244 plots=True batch=16

!yolo task=detect mode=val model=runs/detect/train/weights/best.pt data=data.yaml

!yolo task=detect mode=predict model=runs/detect/train/weights/best.pt data=data.yaml conf =0.5 source = testing/

# Commented out IPython magic to ensure Python compatibility.
#Checking with other image
import numpy
import cv2 as cv
# %cd /content/drive/MyDrive/Car_dataset/Cars Detection
model = YOLO('runs/detect/train/weights/best.pt')
cv_image = cv.imread('ybs.jpg')
result_img = model.predict(cv_image, imgsz=320, conf=0.5)
result_img[0].plot()

result.orig_img

model = YOLO('runs/detect/train/weights/best.pt')
model.info()